<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE WorkFlowDefinition SYSTEM "wfdef4.dtd">
<WorkFlowDefinition ApiVersion="4.0"
Origin="JavaAPI"
	Subject="&quot;aprobacion-credito&quot;"
	Description="aprobar o denegar un credito"
	Name="capacitacion-api-process"
	DisableEmailNotification="false"
	AuthorTool="Process Designer"
	OtherAuthorTools=""
	versionAgnostic="false"
	validateUsingSchema="true"
	validateFlag="true"
	transferFlag="true">
	<Field
		Name="Nombre"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Edad"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Monto"
		ValueExpr="0"
		Type="int"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Identificacion"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TipoIdentificacion"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Status"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="FechaSolicitud"
		ValueExpr="null(time)"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Milestone
		Name="InicioSolicitudEstudio"
		Message="&quot;Solicitud para estudio de credito&quot;"
		Level="1"/>
	<Milestone
		Name="EvaluacionEstudio"
		Message="&quot;Se completa evaluacion de estudio de credito aprobado&quot;"
		Level="1"/>
	<Map
		Name="Workflow"
		MaxStepId="36" >
		<Step
			StepId="0"
			Name="LaunchStep"
			XCoordinate="23"
			YCoordinate="20"
			RequestedInterface="Navigator Launch Processor (default)"
			PostMilestone="InicioSolicitudEstudio"
			JoinType="none"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Parameter
				Name="TipoIdentificacion"
				ValueExpr="TipoIdentificacion"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Nombre"
				ValueExpr="Nombre"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Monto"
				ValueExpr="Monto"
				Type="int"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Identificacion"
				ValueExpr="Identificacion"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="FechaSolicitud"
				ValueExpr="FechaSolicitud"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Edad"
				ValueExpr="Edad"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="0"
				DestinationStepId="3"
				RouteId="8"/>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="1"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<Step
			StepId="3"
			Name="EvaluarSolicitud"
			XCoordinate="238"
			YCoordinate="21"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="Inbox"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Participant Val="F_Originator" />
			<Parameter
				Name="TipoIdentificacion"
				ValueExpr="TipoIdentificacion"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Nombre"
				ValueExpr="Nombre"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Monto"
				ValueExpr="Monto"
				Type="int"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Identificacion"
				ValueExpr="Identificacion"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="FechaSolicitud"
				ValueExpr="FechaSolicitud"
				Type="time"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Edad"
				ValueExpr="Edad"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Route
				SourceStepId="3"
				DestinationStepId="5"
				RouteId="1"
				Condition="Status = &quot;Aprobado&quot;"/>
			<Route
				SourceStepId="3"
				DestinationStepId="30"
				RouteId="5"/>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<Step
			StepId="5"
			Name="Desembolsar"
			XCoordinate="435"
			YCoordinate="20"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="Inbox"
			PreMilestone="EvaluacionEstudio"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Participant Val="F_Originator" />
			<Parameter
				Name="TipoIdentificacion"
				ValueExpr="TipoIdentificacion"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Nombre"
				ValueExpr="Nombre"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Monto"
				ValueExpr="Monto"
				Type="int"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Identificacion"
				ValueExpr="Identificacion"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="FechaSolicitud"
				ValueExpr="FechaSolicitud"
				Type="time"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Edad"
				ValueExpr="Edad"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Route
				SourceStepId="5"
				DestinationStepId="35"
				RouteId="7"/>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<CompoundStep
			StepId="30"
			Name="TerminateProcess"
			XCoordinate="238"
			YCoordinate="135"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="31"
				Action="terminateProcess">
			</Instruction>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_IconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="6"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StartIconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/start_terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepPropertiesPanelClass"
					Type="string"
					IsArray="false">
						<Value Val="filenet.vw.toolkit.design.property.steps.systeminstructions.VWTerminateProcessPropertiesPanel"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="35"
			Name="TerminateProcess"
			XCoordinate="589"
			YCoordinate="20"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="36"
				Action="terminateProcess">
			</Instruction>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_IconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="6"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StartIconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/start_terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepPropertiesPanelClass"
					Type="string"
					IsArray="false">
						<Value Val="filenet.vw.toolkit.design.property.steps.systeminstructions.VWTerminateProcessPropertiesPanel"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
	</Map>
</WorkFlowDefinition>
